- name: Install fail2ban
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Configure fail2ban jails
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Ensure fail2ban service is started and enabled
  service:
    name: fail2ban
    state: started
    enabled: yes
